version: '3.8'
services:
  codecritic-j:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - AZURE_AI_FOUNDRY_ENDPOINT=${AZURE_AI_FOUNDRY_ENDPOINT}
      - AZURE_AI_FOUNDRY_KEY=${AZURE_AI_FOUNDRY_KEY}
      - AZURE_AI_FOUNDRY_DEPLOYMENT_ID=${AZURE_AI_FOUNDRY_DEPLOYMENT_ID}
    restart: unless-stopped 